---
- name: Using first module - file
  hosts: all
  gather_facts: yes

  vars:
    my_directory: /tmp/new_dir

  tasks:

    - name: Check if directory exists
      stat:
        path: "{{ my_directory }}"
      register: my_dir

    - debug:
        var: my_dir

    - name: "Touch file inside if directory {{ my_directory }} exists"
      file:
        path: "{{ my_directory }}/my_file.txt"
        state: touch
        mode: u+rw,g-wx,o-rwx
      when: my_dir.stat.exists
...